### PR TITLE
Fixed 404 for carnage.github.io

### PR DESCRIPTION
**Pull request by JohnnyCrazy**
The trailing / leads to a 404 page

### CODE REVIEW

**Comment by ivanakimov** [comment]
You have to have `grunt` running while modifying the template. That way it auto-generates all the pages based on that template. If you just modify the source template, that won't update the site.

**Comment by JohnnyCrazy** [comment]
@ivanakimov Ah, didn't have a look at the build-process, thought that was automatic or something. Gonna push the follow up ASAP :+1:

**Comment by JohnnyCrazy** [comment]
Fixed @ivanakimov

**Comment by ivanakimov** [comment]
Yeah, it's the repo setup that needs updating, not ideal right now :P Thank you for the PR!

**Pull request merged**
