### PR TITLE
Add Factor language list item at index.html

### PR DESCRIPTION
**Pull request by KennethanCeyer**
#### added

- [Factor](https://factorcode.org/) language info at index.html

### CODE REVIEW

**Comment by ivanakimov** [comment]
Hey @KennethanCeyer, if I understand correctly this is a new implementation in Factor? The best way to add it is to modify links/authors in `src/*` and then run `npm run production` to generate static files.

**Comment by KennethanCeyer** [comment]
@ivanakimov 
No, There seem a new language `Factor` is supported at `linguist` of GitHub
But there is no description in the hashid page

screenshot 2019-06-29 오후 11 44 33

So I just added a small text link on the last of a link after Lolcode :neckbeard:

**Comment by ivanakimov** [comment]
@KennethanCeyer, ah I get it -- cool. Yeah, the file to be modified for that is `src/template.html` and then you have to run `npm run production` so it generates a bunch of static files.

**Comment by KennethanCeyer** [comment]
@ivanakimov Oh, thank you for the describing.
Okay, I will make a new commit to follow that instruction :)

**Comment by KennethanCeyer** [comment]
screenshot 2019-07-02 오전 1 55 46

Okay It's done :)

**Pull request merged**
