### PR TITLE
Add Julia Implementation

### PR DESCRIPTION
**Pull request by antimon2**
I've implemented Hashids in [Julia](https://julialang.org): [Source code](https://github.com/antimon2/Hashids.jl) / [Package Docs](https://pkg.julialang.org/docs/Hashids/)

I sent this PR to update the hashids' website to list Julia entry. Please review this.

Thanks.

### CODE REVIEW

**Comment by antimon2** [comment]
> @antimon2 did you also verify that the output is the same for the edge cases (custom alphabets, etc) between your implementation and one of the pre-existing ones?

Yes, I checked the outputs between my implementation and that of [JavaScript](https://github.com/niieani/hashids.js) (with Node.js), [Python](https://github.com/davidaurelio/hashids-python), etc.

**Comment by jd327** [comment]
@antimon2 Thanks for the port and the PR. Looks good to me, if you can add Julia to https://github.com/hashids/hashids.github.io/blob/master/public/css/src/_section-header.scss#L87 we should be good to go!

---

@niieani Thanks for the ping and taking a look too! :)

**Comment by antimon2** [comment]
@jd327 Edit .scss. I checked the highlighting locally. Is that OK?

**Comment by jd327** [comment]
Thanks @antimon2!

**Pull request merged**
