### PR TITLE
Remove Laravel 4 package

### PR DESCRIPTION
**Pull request by vinkla**
Laravel 4 is old and the package isn't maintained anymore.

### CODE REVIEW

**Comment by ivanakimov** [comment]
Laravel 4 might be old, but I'm sure there's still people using it. I don't see a need to remove it.

**Comment by vinkla** [comment]
People (including myself) are still using it with Laravel 4. Though, new users probably wont use it or shouldn't use it. Anyone using the Laravel 4 integration still knows where to find it but IMO we should encourage new users of Hashids to use the latest version of Laravel.

**Comment by vinkla** [comment]
Do you want to move on this or should we close it?

**Comment by ivanakimov** [comment]
Yeah, all good points, but honestly I don't see the urgency to remove the Laravel 4 link (it's not that old yet). If you want to switch them around so Laravel 5 is first, I'm all good with that. Other than that, it doesn't hurt to still link to it (and new devs are probably well aware that higher version is what they should be using).

**Comment by vinkla** [comment]
Okay, I see your point. Lets leave it like it is for now.

**Pull request closed without merging**
